[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Let client-side routes work in prod preview
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Tell Netlify Dev how to run Vite locally
[dev]
  framework = "#custom"
  command = "vite"
  targetPort = 5173
  port = 8888
